source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LIHLogManager_Example', :exclusive => true do
  pod 'LIHLogManager', :path => '../'
end

target 'LIHLogManager_Tests', :exclusive => true do
  pod 'LIHLogManager', :path => '../'

  
end
